# -*- coding: utf-8 -*-
"""Copy of resnet01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEbMNdo__935wzYMu_4PTIvgF6trH9Xw
"""

print("hi")

import torch
import pandas as pd
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import torch.optim as optim
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader

# Check for GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

dataset_path = '/content/drive/MyDrive/Final_Dataset'


dataset_path = '/content/drive/Shareddrives/Final_Dataset'

dataset_path = '/content/drive/MyDrive/../Shared with me/Final_Dataset'

import os

dataset_path = '/content/drive/MyDrive/Final_Dataset'

print("Main folder contents:", os.listdir(dataset_path))
print("Total Fake images:", len(os.listdir(f"{dataset_path}/Fake")))
print("Total Real images:", len(os.listdir(f"{dataset_path}/Real")))

import pandas as pd

df = pd.read_csv(f"{dataset_path}/dataset.csv")
print(df.shape)
print(df.head())
print(df['label'].value_counts())

print(df.columns)
print(df.head(2))

import shutil
import os
from tqdm.notebook import tqdm

# Check if the directory exists before attempting to remove it
if os.path.exists('/content/Final_Dataset'):
    print("🗑️ Removing incomplete copy...")
    shutil.rmtree('/content/Final_Dataset')
    print("✅ Removed!")

src = '/content/drive/MyDrive/Final_Dataset'
dst = '/content/Final_Dataset'
os.makedirs(dst, exist_ok=True)

shutil.copy2(os.path.join(src, 'dataset.csv'), os.path.join(dst, 'dataset.csv'))
print("📄 CSV copied!")

for folder in ['Real', 'Fake']:
    src_folder = os.path.join(src, folder)
    dst_folder = os.path.join(dst, folder)
    os.makedirs(dst_folder, exist_ok=True)

    files = os.listdir(src_folder)
    print(f"\n📁 Copying {folder} ({len(files)} files)...")

    for file in tqdm(files, desc=folder, unit="img"):
        shutil.copy2(os.path.join(src_folder, file), os.path.join(dst_folder, file))

    print(f"✅ {folder} done!")

print("\n🎉 Dataset ready!")

df['path'] = df['path'].str.replace(
    '/kaggle/input/stylegan-and-stylegan2-combined-dataset/Final Dataset',
    '/content/Final_Dataset',
    regex=False
)

print(df['path'].iloc[0])
print(f"File exists : {os.path.exists(df['path'].iloc[0])}")

import os

print(os.listdir('/content/Final_Dataset'))

import os

real_files = os.listdir('/content/Final_Dataset/Real')
fake_files = os.listdir('/content/Final_Dataset/Fake')

print("Real count:", len(real_files))
print("Fake count:", len(fake_files))

print("\nFirst 3 Real files:", real_files[:3])
print("First 3 Fake files:", fake_files[:3])

print("\nDF path sample:", df['path'].iloc[0])

from sklearn.model_selection import train_test_split

X = df['path']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"X_train : {len(X_train)}")
print(f"X_test  : {len(X_test)}")

from torchvision import transforms

train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),          # ResNet expects 224x224
    transforms.RandomHorizontalFlip(),      # light augmentation
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],   # ImageNet mean
                         [0.229, 0.224, 0.225])    # ImageNet std
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

from torch.utils.data import Dataset
from PIL import Image
import torch

class CustomDataset(Dataset):

    def __init__(self, filepaths, labels, transform=None):
        self.filepaths = filepaths.reset_index(drop=True)
        self.labels    = labels.reset_index(drop=True)
        self.transform = transform
        self.label_map = {"Fake": 0, "Real": 1}

    def __len__(self):
        return len(self.filepaths)

    def __getitem__(self, idx):
        img_path = self.filepaths[idx]
        image    = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        label = self.label_map[self.labels[idx]]
        return image, torch.tensor(label, dtype=torch.long)

from torch.utils.data import DataLoader

train_dataset = CustomDataset(X_train, y_train, transform=train_transforms)
test_dataset  = CustomDataset(X_test,  y_test,  transform=test_transforms)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True,  pin_memory=True, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False, pin_memory=True, num_workers=2)

print(f"Train batches : {len(train_loader)}")
print(f"Test batches  : {len(test_loader)}")

import torch.nn as nn
from torchvision import models

def build_resnet(num_classes=1, freeze_backbone=True):
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)


    if freeze_backbone:
        for param in model.parameters():
            param.requires_grad = False


    for param in model.layer4.parameters():
        param.requires_grad = True


    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(in_features, 256),
        nn.BatchNorm1d(256),
        nn.ReLU(),
        nn.Dropout(p=0.4),
        nn.Linear(256, num_classes)
    )
    return model

model = build_resnet(num_classes=1, freeze_backbone=True)
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"Trainable params : {trainable:,} / {total:,}")

import torch.optim as optim

device        = torch.device("cuda" if torch.cuda.is_available() else "cpu")
epochs        = 50
learning_rate = 1e-3

model     = build_resnet(num_classes=1, freeze_backbone=True).to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=learning_rate,
    weight_decay=1e-4
)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3
)

from tqdm import tqdm

best_val_loss   = float('inf')
patience        = 5
patience_counter = 0

for epoch in range(epochs):


    model.train()
    train_loss, train_correct, train_total = 0, 0, 0

    for features, labels in tqdm(train_loader, desc=f"[{epoch+1}/{epochs}] Train"):
        features = features.to(device, non_blocking=True)
        labels   = labels.float().to(device, non_blocking=True)

        optimizer.zero_grad()
        out  = model(features).squeeze(1)
        loss = criterion(out, labels)
        loss.backward()
        optimizer.step()

        train_loss    += loss.item()
        preds          = (torch.sigmoid(out) >= 0.5).int()
        train_correct += (preds == labels.int()).sum().item()
        train_total   += labels.size(0)

    avg_train_loss = train_loss / len(train_loader)
    train_acc      = train_correct / train_total * 100


    model.eval()
    val_loss, val_correct, val_total = 0, 0, 0

    with torch.no_grad():
        for features, labels in test_loader:
            features = features.to(device)
            labels   = labels.float().to(device)

            out  = model(features).squeeze(1)
            loss = criterion(out, labels)

            val_loss    += loss.item()
            preds        = (torch.sigmoid(out) >= 0.5).int()
            val_correct += (preds == labels.int()).sum().item()
            val_total   += labels.size(0)

    avg_val_loss = val_loss / len(test_loader)
    val_acc      = val_correct / val_total * 100

    scheduler.step(avg_val_loss)

    print(f"Epoch {epoch+1:02d} | "
          f"Train Loss: {avg_train_loss:.4f}  Acc: {train_acc:.2f}% | "
          f"Val Loss: {avg_val_loss:.4f}  Acc: {val_acc:.2f}%")

    # ── Early stopping + checkpoint ───────────────────────────
    if avg_val_loss < best_val_loss:
        best_val_loss    = avg_val_loss
        patience_counter = 0
        torch.save(model.state_dict(), "best_resnet_deepfake.pth")
        print("  ✅ Best model saved.")
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print(f"⏹ Early stopping at epoch {epoch+1}")
            break

# Load best weights after training
model.load_state_dict(torch.load("best_resnet_deepfake.pth"))

import torch

def evaluate(model, loader, device):
    model.eval()

    TP = 0
    FP = 0
    FN = 0
    TN = 0

    with torch.no_grad():
        for features, labels in loader:
            features = features.to(device)
            labels   = labels.int().to(device)

            outputs = model(features).squeeze(1)

            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).int()

            TP += ((preds == 1) & (labels == 1)).sum().item()
            FP += ((preds == 1) & (labels == 0)).sum().item()
            FN += ((preds == 0) & (labels == 1)).sum().item()
            TN += ((preds == 0) & (labels == 0)).sum().item()

    # Metrics
    accuracy  = (TP + TN) / (TP + TN + FP + FN) * 100

    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0

    f1_score  = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0 else 0
    )

    return accuracy, precision, recall, f1_score

train_acc, train_prec, train_rec, train_f1 = evaluate(model, train_loader, device)
test_acc,  test_prec,  test_rec,  test_f1  = evaluate(model, test_loader, device)

print(f"Train Accuracy : {train_acc:.2f}%")
print(f"Train Precision: {train_prec:.4f}")
print(f"Train Recall   : {train_rec:.4f}")
print(f"Train F1 Score : {train_f1:.4f}\n")

print(f"Test Accuracy  : {test_acc:.2f}%")
print(f"Test Precision : {test_prec:.4f}")
print(f"Test Recall    : {test_rec:.4f}")
print(f"Test F1 Score  : {test_f1:.4f}")

import pickle

model.eval()
model.to("cpu")

with open("deepfake_model.pkl", "wb") as f:
    pickle.dump(model, f)

import torch.nn as nn
from torchvision import models

def build_resnet(num_classes=1, freeze_backbone=True):
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)


    if freeze_backbone:
        for param in model.parameters():
            param.requires_grad = False


    for param in model.layer4.parameters():
        param.requires_grad = True


    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(in_features, 256),
        nn.BatchNorm1d(256),
        nn.ReLU(),
        nn.Dropout(p=0.4),
        nn.Linear(256, num_classes)
    )
    return model

model = build_resnet(num_classes=1, freeze_backbone=True)
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"Trainable params : {trainable:,} / {total:,}")

from torchvision import transforms

train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

!pip install nbformat

!pip install nbformat

